name: LuaRocks release
on:
  push:
    tags:
      - "*"

jobs:
  pongo-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kong_version:
        - "2.8.x"
        - "3.0.x"
    steps:
    - uses: actions/checkout@v3
    - uses: Kong/kong-pongo-action@v1
      with:
        kong_version: ${{ matrix.kong_version }}

    - run: pongo run

  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v4
        with:
          name: kong-event-pub-plugin
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}